#!/bin/sh

#
#   ██████  █████  ████████ ██     ██ ███    ███ 
#  ██      ██   ██    ██    ██     ██ ████  ████ 
#  ██      ███████    ██    ██  █  ██ ██ ████ ██ 
#  ██      ██   ██    ██    ██ ███ ██ ██  ██  ██ 
#   ██████ ██   ██    ██     ███ ███  ██      ██ By l1amsi
#
#    : https://github.com/itsl1amsi
#                                                

bspc rule -r "*"

# Autostart
$HOME/.config/bspwm/autostart.sh

# Colors
mauve='#cba6f7'
red='#f38ba8'
blue='#89b4fa'
lavender='#b4befe'
surface1='#45475a'

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width          3
bspc config normal_border_color   $surface1
bspc config focused_border_color  $blue
bspc config window_gap            12
bspc config top_padding           35
bspc config split_ratio          0.50
bspc config borderless_monocle   true # remove the borders if the focused window is fullscreen
bspc config gapless_monocle      true # remove the gaps (spaces) between the windows if the focused window is fs
bspc config automatic_scheme     alternate

# Preselect
bspc config presel_feedback_color $blue

# Cursor
bspc config focus_follows_pointer true # the focus follow the cursor
bspc config pointer_follows_focus true # the cursor follow the focused window


bspc rule -a "Virtual Machine Manager" desktop='^6' state=tiled follow=on
bspc rule -a Nitrogen state=floating
bspc rule -a Munadi state=floating
bspc rule -a Zathura state=tiled
